-- Bounded Tech Assistant memory, supplier knowledge, and safe POS lookup tools.
-- Run once after 044_tech_assistant_permission.sql.

begin;

create table if not exists public.assistant_settings (
  id boolean primary key default true check (id = true),
  default_language text not null default 'en' check (default_language in ('en', 'ta')),
  response_style text not null default 'concise' check (response_style in ('brief', 'concise', 'detailed')),
  save_conversations boolean not null default true,
  conversation_retention_days integer not null default 30 check (conversation_retention_days between 1 and 90),
  max_conversations_per_staff integer not null default 10 check (max_conversations_per_staff between 1 and 20),
  auto_speak_answers boolean not null default false,
  custom_instructions text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references public.staff(id) on delete set null
);

insert into public.assistant_settings(id) values(true) on conflict(id) do nothing;

create table if not exists public.assistant_supplier_knowledge (
  id uuid primary key default gen_random_uuid(),
  supplier_name text not null,
  title text not null,
  content text not null,
  tags text[] not null default '{}'::text[],
  is_active boolean not null default true,
  created_by uuid references public.staff(id) on delete set null,
  updated_by uuid references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assistant_supplier_name_length check (char_length(supplier_name) between 1 and 120),
  constraint assistant_supplier_title_length check (char_length(title) between 1 and 180),
  constraint assistant_supplier_content_length check (char_length(content) between 1 and 12000)
);

create index if not exists assistant_supplier_knowledge_updated_idx
  on public.assistant_supplier_knowledge(updated_at desc);

create table if not exists public.assistant_conversations (
  id uuid primary key default gen_random_uuid(),
  staff_id uuid not null references public.staff(id) on delete cascade,
  title text not null,
  language text not null default 'en' check (language in ('en', 'ta')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists assistant_conversations_staff_updated_idx
  on public.assistant_conversations(staff_id, updated_at desc);

create table if not exists public.assistant_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.assistant_conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint assistant_message_content_length check (char_length(content) between 1 and 6000)
);

create index if not exists assistant_messages_conversation_created_idx
  on public.assistant_messages(conversation_id, created_at, id);

alter table public.assistant_settings enable row level security;
alter table public.assistant_supplier_knowledge enable row level security;
alter table public.assistant_conversations enable row level security;
alter table public.assistant_messages enable row level security;

revoke all on public.assistant_settings from anon, authenticated;
revoke all on public.assistant_supplier_knowledge from anon, authenticated;
revoke all on public.assistant_conversations from anon, authenticated;
revoke all on public.assistant_messages from anon, authenticated;

create or replace function public.assistant_is_admin_v45()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists(
    select 1
    from public.staff s
    where s.id = public.current_pos_staff_id_v38()
      and s.role = 'admin'
      and s.is_active
  );
$$;

create or replace function public.assistant_get_settings_v45()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  settings_row public.assistant_settings%rowtype;
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  if not public.has_pos_permission_v38('use_ai_assistant') then
    raise exception 'The active user does not have Tech Assistant permission';
  end if;
  select * into settings_row from public.assistant_settings s where s.id = true;
  return to_jsonb(settings_row);
end;
$$;

create or replace function public.admin_save_assistant_settings_v45(p_settings jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  admin_id uuid := public.current_pos_staff_id_v38();
  settings_row public.assistant_settings%rowtype;
  requested_language text := lower(coalesce(nullif(p_settings ->> 'default_language', ''), 'en'));
  requested_style text := lower(coalesce(nullif(p_settings ->> 'response_style', ''), 'concise'));
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  if not public.assistant_is_admin_v45() then raise exception 'Only an active admin can change assistant settings'; end if;
  if requested_language not in ('en', 'ta') then requested_language := 'en'; end if;
  if requested_style not in ('brief', 'concise', 'detailed') then requested_style := 'concise'; end if;

  insert into public.assistant_settings(
    id, default_language, response_style, save_conversations,
    conversation_retention_days, max_conversations_per_staff,
    auto_speak_answers, custom_instructions, updated_at, updated_by
  ) values (
    true,
    requested_language,
    requested_style,
    coalesce((p_settings ->> 'save_conversations')::boolean, true),
    greatest(1, least(coalesce((p_settings ->> 'conversation_retention_days')::integer, 30), 90)),
    greatest(1, least(coalesce((p_settings ->> 'max_conversations_per_staff')::integer, 10), 20)),
    coalesce((p_settings ->> 'auto_speak_answers')::boolean, false),
    left(coalesce(p_settings ->> 'custom_instructions', ''), 2000),
    now(),
    admin_id
  )
  on conflict(id) do update set
    default_language = excluded.default_language,
    response_style = excluded.response_style,
    save_conversations = excluded.save_conversations,
    conversation_retention_days = excluded.conversation_retention_days,
    max_conversations_per_staff = excluded.max_conversations_per_staff,
    auto_speak_answers = excluded.auto_speak_answers,
    custom_instructions = excluded.custom_instructions,
    updated_at = now(),
    updated_by = admin_id
  returning * into settings_row;

  if not settings_row.save_conversations then
    delete from public.assistant_conversations;
  end if;
  return to_jsonb(settings_row);
end;
$$;

create or replace function public.admin_list_assistant_knowledge_v45()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  result jsonb;
begin
  if not public.assistant_is_admin_v45() then raise exception 'Only an active admin can manage supplier knowledge'; end if;
  select coalesce(jsonb_agg(to_jsonb(k) order by k.updated_at desc), '[]'::jsonb)
    into result
  from public.assistant_supplier_knowledge k;
  return result;
end;
$$;

create or replace function public.admin_save_assistant_knowledge_v45(p_entry jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  admin_id uuid := public.current_pos_staff_id_v38();
  entry_id uuid := nullif(p_entry ->> 'id', '')::uuid;
  entry_tags text[];
  saved_row public.assistant_supplier_knowledge%rowtype;
begin
  if not public.assistant_is_admin_v45() then raise exception 'Only an active admin can manage supplier knowledge'; end if;

  select coalesce(array_agg(left(trim(tag_value), 60)) filter (where trim(tag_value) <> ''), '{}'::text[])
    into entry_tags
  from jsonb_array_elements_text(coalesce(p_entry -> 'tags', '[]'::jsonb)) as tags(tag_value);

  if trim(coalesce(p_entry ->> 'supplier_name', '')) = '' then raise exception 'Supplier name is required'; end if;
  if trim(coalesce(p_entry ->> 'title', '')) = '' then raise exception 'List title is required'; end if;
  if trim(coalesce(p_entry ->> 'content', '')) = '' then raise exception 'Supplier list content is required'; end if;
  if entry_id is null and (select count(*) from public.assistant_supplier_knowledge) >= 100 then
    raise exception 'Supplier memory is limited to 100 lists. Edit or remove an old list first';
  end if;

  if entry_id is null then
    insert into public.assistant_supplier_knowledge(
      supplier_name, title, content, tags, is_active, created_by, updated_by
    ) values (
      left(trim(p_entry ->> 'supplier_name'), 120),
      left(trim(p_entry ->> 'title'), 180),
      left(trim(p_entry ->> 'content'), 12000),
      entry_tags,
      coalesce((p_entry ->> 'is_active')::boolean, true),
      admin_id,
      admin_id
    ) returning * into saved_row;
  else
    update public.assistant_supplier_knowledge k set
      supplier_name = left(trim(p_entry ->> 'supplier_name'), 120),
      title = left(trim(p_entry ->> 'title'), 180),
      content = left(trim(p_entry ->> 'content'), 12000),
      tags = entry_tags,
      is_active = coalesce((p_entry ->> 'is_active')::boolean, true),
      updated_by = admin_id,
      updated_at = now()
    where k.id = entry_id
    returning * into saved_row;
    if saved_row.id is null then raise exception 'Supplier knowledge entry was not found'; end if;
  end if;
  return to_jsonb(saved_row);
end;
$$;

create or replace function public.admin_delete_assistant_knowledge_v45(p_entry_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.assistant_is_admin_v45() then raise exception 'Only an active admin can manage supplier knowledge'; end if;
  delete from public.assistant_supplier_knowledge k where k.id = p_entry_id;
  return found;
end;
$$;

create or replace function public.assistant_search_context_v45(p_query text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  clean_query text := left(trim(coalesce(p_query, '')), 500);
  show_cost boolean := false;
  products_json jsonb := '[]'::jsonb;
  knowledge_json jsonb := '[]'::jsonb;
begin
  if not public.has_pos_permission_v38('use_ai_assistant') then
    raise exception 'The active user does not have Tech Assistant permission';
  end if;
  show_cost := public.assistant_is_admin_v45() or public.has_pos_permission_v38('manage_products');

  with terms as (
    select distinct regexp_replace(lower(token.term_value), '^[[:punct:]]+|[[:punct:]]+$', '', 'g') as term
    from regexp_split_to_table(clean_query, E'\\s+') as token(term_value)
    where char_length(regexp_replace(token.term_value, '^[[:punct:]]+|[[:punct:]]+$', '', 'g')) >= 2
      and lower(token.term_value) not in ('what','which','where','have','with','this','that','there','stock','price','available','need','want','show','find','give','please','does','shop','item')
  ), ranked as (
    select p.*,
      case when lower(coalesce(p.item_code, '')) = lower(clean_query) then 200
           when lower(coalesce(p.barcode, '')) = lower(clean_query) then 190
           when lower(coalesce(p.name, '')) like '%' || lower(clean_query) || '%' then 120
           else 10 * (select count(*) from terms t where lower(concat_ws(' ', p.item_code, p.name, p.barcode, p.category_path)) like '%' || t.term || '%') end as score
    from public.product_stock_view p
    where p.is_active
      and (
        lower(concat_ws(' ', p.item_code, p.name, p.barcode, p.category_path)) like '%' || lower(clean_query) || '%'
        or exists(select 1 from terms t where lower(concat_ws(' ', p.item_code, p.name, p.barcode, p.category_path)) like '%' || t.term || '%')
      )
  ), limited as (
    select * from ranked where score > 0 order by score desc, item_code limit 12
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'product_id', p.product_id,
    'item_code', p.item_code,
    'name', p.name,
    'category', p.category_path,
    'selling_price', p.selling_price,
    'average_cost', case when show_cost then p.avg_cost else null end,
    'track_inventory', p.track_inventory,
    'sellable_qty', p.sellable_qty,
    'reserved_qty', p.reserved_qty,
    'available_qty', p.available_qty,
    'in_transit_qty', p.in_transit_qty,
    'damaged_qty', p.damaged_qty,
    'warranty_months', p.warranty_months
  ) order by p.score desc, p.item_code), '[]'::jsonb)
  into products_json from limited p;

  with terms as (
    select distinct regexp_replace(lower(token.term_value), '^[[:punct:]]+|[[:punct:]]+$', '', 'g') as term
    from regexp_split_to_table(clean_query, E'\\s+') as token(term_value)
    where char_length(regexp_replace(token.term_value, '^[[:punct:]]+|[[:punct:]]+$', '', 'g')) >= 2
  ), ranked as (
    select k.*,
      (select count(*) from terms t where lower(concat_ws(' ', k.supplier_name, k.title, array_to_string(k.tags, ' '), k.content)) like '%' || t.term || '%') as score
    from public.assistant_supplier_knowledge k
    where k.is_active
  ), limited as (
    select * from ranked where score > 0 order by score desc, updated_at desc limit 6
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', k.id,
    'supplier_name', k.supplier_name,
    'title', k.title,
    'content', left(k.content, 4000),
    'tags', k.tags,
    'updated_at', k.updated_at
  ) order by k.score desc, k.updated_at desc), '[]'::jsonb)
  into knowledge_json from limited k;

  return jsonb_build_object('products', products_json, 'supplier_knowledge', knowledge_json, 'checked_at', now());
end;
$$;

create or replace function public.assistant_list_conversations_v45()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_staff_id uuid := public.current_pos_staff_id_v38();
  retention_days integer;
  result jsonb;
begin
  if not public.has_pos_permission_v38('use_ai_assistant') then raise exception 'Tech Assistant permission required'; end if;
  select s.conversation_retention_days into retention_days from public.assistant_settings s where s.id = true;
  delete from public.assistant_conversations c
    where c.staff_id = current_staff_id and c.updated_at < now() - make_interval(days => coalesce(retention_days, 30));
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', c.id, 'title', c.title, 'language', c.language,
    'created_at', c.created_at, 'updated_at', c.updated_at,
    'message_count', (select count(*) from public.assistant_messages m where m.conversation_id = c.id)
  ) order by c.updated_at desc), '[]'::jsonb)
  into result
  from public.assistant_conversations c
  where c.staff_id = current_staff_id;
  return result;
end;
$$;

create or replace function public.assistant_get_conversation_v45(p_conversation_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  current_staff_id uuid := public.current_pos_staff_id_v38();
  result jsonb;
begin
  if not public.has_pos_permission_v38('use_ai_assistant') then raise exception 'Tech Assistant permission required'; end if;
  if not exists(select 1 from public.assistant_conversations c where c.id = p_conversation_id and c.staff_id = current_staff_id) then
    raise exception 'Conversation was not found';
  end if;
  select jsonb_build_object(
    'conversation', jsonb_build_object('id', c.id, 'title', c.title, 'language', c.language, 'updated_at', c.updated_at),
    'messages', coalesce((select jsonb_agg(jsonb_build_object(
      'id', m.id, 'role', m.role, 'text', m.content, 'metadata', m.metadata, 'created_at', m.created_at
    ) order by m.created_at, m.id) from public.assistant_messages m where m.conversation_id = c.id), '[]'::jsonb)
  ) into result
  from public.assistant_conversations c
  where c.id = p_conversation_id and c.staff_id = current_staff_id;
  return result;
end;
$$;

create or replace function public.assistant_save_exchange_v45(
  p_conversation_id uuid,
  p_question text,
  p_answer text,
  p_language text default 'en',
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_staff_id uuid := public.current_pos_staff_id_v38();
  settings_row public.assistant_settings%rowtype;
  conversation_row public.assistant_conversations%rowtype;
  requested_language text := case when lower(p_language) = 'ta' then 'ta' else 'en' end;
begin
  if not public.has_pos_permission_v38('use_ai_assistant') then raise exception 'Tech Assistant permission required'; end if;
  select * into settings_row from public.assistant_settings s where s.id = true;
  if not coalesce(settings_row.save_conversations, true) then return null; end if;
  if trim(coalesce(p_question, '')) = '' or trim(coalesce(p_answer, '')) = '' then return null; end if;

  delete from public.assistant_conversations c
    where c.staff_id = current_staff_id and c.updated_at < now() - make_interval(days => coalesce(settings_row.conversation_retention_days, 30));

  if p_conversation_id is not null then
    select * into conversation_row from public.assistant_conversations c
      where c.id = p_conversation_id and c.staff_id = current_staff_id for update;
  end if;
  if conversation_row.id is null then
    insert into public.assistant_conversations(staff_id, title, language)
    values(current_staff_id, left(regexp_replace(trim(p_question), E'\\s+', ' ', 'g'), 80), requested_language)
    returning * into conversation_row;
  end if;

  insert into public.assistant_messages(conversation_id, role, content)
  values(conversation_row.id, 'user', left(trim(p_question), 2000));
  insert into public.assistant_messages(conversation_id, role, content, metadata)
  values(conversation_row.id, 'assistant', left(trim(p_answer), 6000), coalesce(p_metadata, '{}'::jsonb));
  update public.assistant_conversations c set updated_at = now(), language = requested_language where c.id = conversation_row.id;

  delete from public.assistant_messages m
  where m.conversation_id = conversation_row.id
    and m.id in (
      select old_message.id from public.assistant_messages old_message
      where old_message.conversation_id = conversation_row.id
      order by old_message.created_at desc, old_message.id desc
      offset 30
    );

  delete from public.assistant_conversations c
  where c.staff_id = current_staff_id
    and c.id in (
      select old_conversation.id from public.assistant_conversations old_conversation
      where old_conversation.staff_id = current_staff_id
      order by old_conversation.updated_at desc
      offset coalesce(settings_row.max_conversations_per_staff, 10)
    );

  return jsonb_build_object('id', conversation_row.id, 'title', conversation_row.title, 'language', requested_language, 'updated_at', now());
end;
$$;

create or replace function public.assistant_delete_conversation_v45(p_conversation_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.has_pos_permission_v38('use_ai_assistant') then raise exception 'Tech Assistant permission required'; end if;
  delete from public.assistant_conversations c
  where c.id = p_conversation_id and c.staff_id = public.current_pos_staff_id_v38();
  return found;
end;
$$;

revoke all on function public.assistant_is_admin_v45() from public;
revoke all on function public.assistant_get_settings_v45() from public;
revoke all on function public.admin_save_assistant_settings_v45(jsonb) from public;
revoke all on function public.admin_list_assistant_knowledge_v45() from public;
revoke all on function public.admin_save_assistant_knowledge_v45(jsonb) from public;
revoke all on function public.admin_delete_assistant_knowledge_v45(uuid) from public;
revoke all on function public.assistant_search_context_v45(text) from public;
revoke all on function public.assistant_list_conversations_v45() from public;
revoke all on function public.assistant_get_conversation_v45(uuid) from public;
revoke all on function public.assistant_save_exchange_v45(uuid, text, text, text, jsonb) from public;
revoke all on function public.assistant_delete_conversation_v45(uuid) from public;

grant execute on function public.assistant_is_admin_v45() to authenticated;
grant execute on function public.assistant_get_settings_v45() to authenticated;
grant execute on function public.admin_save_assistant_settings_v45(jsonb) to authenticated;
grant execute on function public.admin_list_assistant_knowledge_v45() to authenticated;
grant execute on function public.admin_save_assistant_knowledge_v45(jsonb) to authenticated;
grant execute on function public.admin_delete_assistant_knowledge_v45(uuid) to authenticated;
grant execute on function public.assistant_search_context_v45(text) to authenticated;
grant execute on function public.assistant_list_conversations_v45() to authenticated;
grant execute on function public.assistant_get_conversation_v45(uuid) to authenticated;
grant execute on function public.assistant_save_exchange_v45(uuid, text, text, text, jsonb) to authenticated;
grant execute on function public.assistant_delete_conversation_v45(uuid) to authenticated;

do $$
begin
  if exists(select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists(select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'assistant_settings') then
      alter publication supabase_realtime add table public.assistant_settings;
    end if;
    if not exists(select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'assistant_supplier_knowledge') then
      alter publication supabase_realtime add table public.assistant_supplier_knowledge;
    end if;
  end if;
end
$$;

notify pgrst, 'reload schema';
commit;
